package dev.revere.alley.feature.cosmetic.internal.repository.impl.mvpmusic;

import dev.revere.alley.AlleyPlugin;
import dev.revere.alley.core.profile.Profile;
import dev.revere.alley.core.profile.ProfileService;
import dev.revere.alley.core.profile.enums.ProfileState;
import dev.revere.alley.feature.music.MusicService;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.player.PlayerResourcePackStatusEvent;
/**
 * @author Ddk1 ClaudeCode
 * @project Alley
 * @since 13/07/2026
 *
 * Pushes the MVP music resource pack to players when they join.
 * The pack must already be generated by {@link ResourcePackBuilder} and
 * the HTTP server started by {@link HttpPackServer}.
 */
public final class PackSender implements Listener {

    private final AlleyPlugin plugin;
    private final HttpPackServer packServer;
    private volatile byte[] cachedSha1;

    public PackSender(AlleyPlugin plugin, HttpPackServer packServer) {
        this.plugin = plugin;
        this.packServer = packServer;
    }

    @EventHandler
    public void onPlayerJoin(PlayerJoinEvent event) {
        // Delay 1s so the client is fully ready before receiving the pack
        org.bukkit.Bukkit.getScheduler().runTaskLater(plugin, () -> {
            String url = packServer.getPackUrl();
            byte[] sha1 = getSha1();

            if (url == null) {
                plugin.getLogger().warning("[Alley] PackSender: url is null, skipping pack push");
                return;
            }
            if (sha1 == null || sha1.length == 0) {
                plugin.getLogger().warning("[Alley] PackSender: sha1 is empty, skipping pack push");
                return;
            }

            plugin.getLogger().info("[Alley] Pushing MVP pack to " + event.getPlayer().getName()
                    + " -> " + url);
            event.getPlayer().setResourcePack(url, sha1, "Alley MVP Music", true);
        }, 20L);
    }

    @EventHandler
    public void onResourcePackLoaded(PlayerResourcePackStatusEvent event) {
        if (event.getStatus() != PlayerResourcePackStatusEvent.Status.SUCCESSFULLY_LOADED) return;

        org.bukkit.Bukkit.getScheduler().runTaskLater(plugin, () -> {
            if (!event.getPlayer().isOnline()) return;
            Profile profile = plugin.getService(ProfileService.class).getProfile(event.getPlayer().getUniqueId());
            if (profile == null || (profile.getState() != ProfileState.LOBBY && profile.getState() != ProfileState.WAITING)) {
                return;
            }
            if (profile.getProfileData().getSettingData().isLobbyMusicEnabled()) {
                plugin.getService(MusicService.class).startMusic(event.getPlayer());
            }
        }, 1L);
    }

    private byte[] getSha1() {
        if (cachedSha1 != null) return cachedSha1;
        String hex = ResourcePackBuilder.getPackSha1(plugin);
        if (hex == null || hex.isEmpty()) {
            plugin.getLogger().warning("[Alley] PackSender: SHA-1 hex is empty");
            return null;
        }
        cachedSha1 = hexToBytes(hex);
        plugin.getLogger().info("[Alley] PackSender: computed SHA-1 = " + hex);
        return cachedSha1;
    }

    private static byte[] hexToBytes(String hex) {
        int len = hex.length();
        byte[] data = new byte[len / 2];
        for (int i = 0; i < len; i += 2) {
            data[i / 2] = (byte) ((Character.digit(hex.charAt(i), 16) << 4)
                    + Character.digit(hex.charAt(i + 1), 16));
        }
        return data;
    }
}
